var fs = require("fs"),
  download = require("image-downloader");

var categories = {
  "access-control": {
    badgereader: "Badge Reader",
    fingerprintreader: "Fingerprint Reader",
    guard: "Guard",
    keyaccess: "Key Access",
    outofservice: "Out Of Service",
    passwordaccess: "Password Access",
    retinascanner: "Retina Scanner",
    voicerecognition: "Voice Recognition",
  },
  accessibility: {
    "assisted.listening": "Assisted Listening",
    braille: "Braille",
    hearing: "Hearing",
    hearingloop: "Hearing Loop",
    signlanginterpreter: "Sign Language Interpreter",
    tdd: "Tdd",
    trs: "Trs",
    volume: "Volume",
    wheelchair: "Wheelchair",
    tactilepaving: "Tactile Paving",
  },
  amenity: {
    atm: "ATM",
    amphitheater: "Amphitheater",
    animalreliefarea: "Animal Relief Area",
    arrivalgate: "Arrival Gate",
    babychanging: "Baby Changing Room",
    baggagecarousel: "Baggage Carousel",
    "baggagecarousel.intl": "Baggage Carousel (international)",
    baggagecarts: "Baggage Carts",
    baggageclaim: "Baggage Claim",
    "baggageclaim.oversize": "Baggage Claim (oversize)",
    baggagerecheck: "Baggage Recheck",
    baggagestorage: "Baggage Storage",
    boardinggate: "Boarding Gate",
    "boardinggate.aircraft": "Boarding Gate (aircraft)",
    "boardinggate.bus": "Boarding Gate (bus)",
    "boardinggate.ferry": "Boarding Gate (ferry)",
    "boardinggate.train": "Boarding Gate (train)",
    bus: "Bus",
    "bus.muni": "Bus (municipal)",
    "bus.national": "Bus (national)",
    businesscenter: "Business Center",
    cabin: "Cabin",
    carrental: "Car Rental",
    caregiver: "Caregiver",
    cashier: "Cashier",
    changemachine: "Change Machine",
    chapel: "Chapel",
    checkin: "Check-in",
    "checkin.selfservice": "Check-in (self-service)",
    "checkin.desk": "Check-in Desk",
    "checkin.desk.oversizebaggage": "Check-in Desk (oversize baggage)",
    "checkin.desk.transfer": "Check-in Desk (transfer)",
    childplayarea: "Child Play Area",
    coinlocker: "Coin Locker",
    copymachine: "Copy Machine",
    defibrillator: "Defibrillator",
    drinkingfountain: "Drinking Fountain",
    eatingdrinking: "Eating & Drinking",
    elevator: "Elevator",
    emergencyshelter: "Emergency Shelter",
    entry: "Entry",
    escalator: "Escalator",
    exhibit: "Exhibit",
    faregate: "Fare Gate",
    "faregate.oversized": "Fare Gate (oversize)",
    fieldofplay: "Field Of Play ",
    "fieldofplay.baseball": "Field Of Play (baseball)",
    "fieldofplay.basketball": "Field Of Play (basketball)",
    "fieldofplay.fieldhockey": "Field Of Play (field hockey)",
    "fieldofplay.americanfootball": "Field Of Play (football)",
    "fieldofplay.icehockey": "Field Of Play (ice hockey)",
    "fieldofplay.rugby": "Field Of Play (rugby)",
    "fieldofplay.soccer": "Field Of Play (soccer)",
    "fieldofplay.softball": "Field Of Play (softball)",
    "fieldofplay.tennis": "Field Of Play (tennis)",
    "fieldofplay.trackfield": "Field Of Play (track & field)",
    "fieldofplay.volleyball": "Field Of Play (volleyball)",
    firealarmpullstation: "Fire Alarm Pull Station",
    fireextinguisher: "Fire Extinguisher",
    firstaid: "First Aid",
    fittingroom: "Fitting Room",
    foodservice: "Food Service",
    gatearea: "Gate Area",
    groundtransportation: "Ground Transportation",
    guestservices: "Guest Services",
    hoteling: "Hoteling",
    immigration: "Immigration",
    information: "Information",
    "information.bid": "Information (bid)",
    "information.carrental": "Information (car rental)",
    "information.hotel": "Information (hotel)",
    "information.mufid": "Information (mufid)",
    "information.mufid.arrivals": "Information (mufid, arrivals)",
    "information.mufid.departures": "Information (mufid, departures)",
    "information.transit": "Information (transit)",
    landmark: "Landmark",
    library: "Library",
    limo: "Limo",
    lostandfound: "Lost & Found",
    mailbox: "Mailbox",
    meditation: "Meditation",
    meetingpoint: "Meeting Point",
    mobilityrescue: "Mobility Rescue",
    mothersroom: "Mothers Room",
    movingwalkway: "Moving Walkway",
    paidarea: "Paid Area",
    parkandride: "Park & Ride",
    parking: "Parking",
    "parking.bicycle": "Parking (bicycle)",
    "parking.compact": "Parking (compact)",
    "parking.ev": "Parking (ev)",
    "parking.longterm": "Parking (long-term)",
    "parking.motorcycle": "Parking (motorcycle)",
    "parking.shortterm": "Parking (short-term)",
    "parking.waitingarea": "Parking (waiting area)",
    payphone: "Pay Phone",
    pedestriancrossing: "Pedestrian Crossing",
    peoplemover: "People Mover",
    phone: "Phone",
    "phone.emergency": "Phone (emergency)",
    photobooth: "Photo Booth",
    platform: "Platform",
    police: "Police",
    powerchargingstation: "Power Charging Station",
    privatelounge: "Private Lounge",
    productreturn: "Product Return",
    "rail.muni": "Rail (municipal)",
    "rail.national": "Rail (national)",
    ramp: "Ramp",
    "reception.desk": "Reception Desk",
    recreation: "Recreation",
    restroom: "Restroom",
    "restroom.family": "Restroom (family)",
    "restroom.female": "Restroom (female)",
    "restroom.male": "Restroom (male)",
    "restroom.transgender": "Restroom (transgender)",
    "restroom.unisex": "Restroom (unisex)",
    rideshare: "Ride Share",
    seat: "Seat",
    seating: "Seating",
    security: "Security",
    "security.checkpoint": "Security Checkpoint",
    "security.inspection": "Security Inspection",
    service: "Service",
    shower: "Shower",
    shuttle: "Shuttle",
    sleepbox: "Sleep Box",
    smokingarea: "Smoking Area",
    stairs: "Stairs",
    storage: "Storage",
    strollerrental: "Stroller Rental",
    studentadmissions: "Student Admissions",
    studentservices: "Student Services",
    swimmingpool: "Swimming Pool",
    "swimmingpool.children": "Swimming Pool (children)",
    "swimmingpool.family": "Swimming Pool (family)",
    taxi: "Taxi",
    ticketing: "Ticketing",
    "ticketing.airline": "Ticketing (airline)",
    "ticketing.bus": "Ticketing (bus)",
    "ticketing.bus.muni": "Ticketing (bus, municipal)",
    "ticketing.bus.national": "Ticketing (bus, national)",
    "ticketing.rail": "Ticketing (rail)",
    "ticketing.rail.muni": "Ticketing (rail, municipal)",
    "ticketing.rail.national": "Ticketing (rail, national)",
    "ticketing.shuttle": "Ticketing (shuttle)",
    traintrack: "Train Track",
    transit: "Transit",
    unspecified: "Unspecified",
    valet: "Valet",
    vendingmachine: "Vending Machine",
    "vendingmachine.trainticket": "Vending Machine (train ticket)",
    wheelchairassist: "Wheelchair Assist",
    wifi: "Wi-Fi",
    yoga: "Yoga",
  },
  building: {
    parking: "Parking",
    transit: "Transit",
    "transit.bus": "Transit (Bus)",
    "transit.train": "Transit (Train)",
    unspecified: "Unspecified",
  },
  direction: {
    directed: "Directed",
    undirected: "Undirected",
  },
  door: {
    door: "Door",
    open: "Open",
    movablepartition: "Movable Partition",
    revolving: "Revolving",
    shutter: "Shutter",
    sliding: "Sliding",
    swinging: "Swinging",
    turnstile: "Turnstile",
    "turnstile.fullheight": "Turnstile Full Height",
    "turnstile.waistheight": "Turnstile Waist Height",
    unspecified: "Unspecified",
  },
  fixture: {
    baggagecarousel: "Baggage Carousel",
    "boardinggate.desk": "Boarding Gate Desk",
    "checkin.desk": "Check-in Desk",
    "checkin.kiosk": "Check-in Kiosk",
    desk: "Desk",
    equipment: "Equipment",
    furniture: "Furniture",
    "immigration.desk": "Immigration Desk",
    "inspection.desk": "Inspection Desk",
    obstruction: "Obstruction",
    securityequipment: "Security Equipment",
    stage: "Stage",
    vegetation: "Vegetation",
    wall: "Wall",
    water: "Water",
  },
  footprint: {
    aerial: "Aerial",
    ground: "Ground",
    subterranean: "Subterranean",
  },
  geofence: {
    concourse: "Concourse",
    geofence: "Geofence",
    paidarea: "Paid Area",
    platform: "Platform",
    postsecurity: "Post-Security",
    presecurity: "Pre-Security",
    terminal: "Terminal",
    underconstruction: "Under Construction",
  },
  level: {
    arrivals: "Arrivals",
    "arrivals.domestic": "Arrivals (domestic)",
    "arrivals.intl": "Arrivals (international)",
    departures: "Departures",
    "departures.domestic": "Departures (domestic)",
    "departures.intl": "Departures (international)",
    parking: "Parking",
    transit: "Transit",
    unspecified: "Unspecified",
  },
  material: {
    wood: "Wood",
    glass: "Glass",
    metal: "Metal",
    gate: "Gate",
  },
  occupant: {
    accessories: "Accessories",
    appliances: "Appliances",
    artgallery: "Artgallery",
    "arts.entertainment": "Arts & Entertainment",
    autopartssupplies: "Auto Parts & Supplies",
    automotive: "Automotive",
    bank: "Bank",
    beautyspas: "Beauty Spas",
    beerwinespirits: "Beer, Wine & Spirits",
    booksmagazinesmusicvideo: "Books, Magazines, Music & Video",
    cafe: "Cafe",
    carrental: "Car Rental",
    "cards.stationery": "Cards & Stationery",
    cinema: "Cinema",
    "clothing.childrens": "Clothing (childrens)",
    "clothing.mens": "Clothing (mens)",
    "clothing.womens": "Clothing (womens)",
    "coffee.tea": "Coffee & Tea",
    cosmetics: "Cosmetics",
    departmentstore: "Department Store",
    drycleaninglaundry: "Dry Cleaning & Laundry",
    education: "Education",
    "eyewear.opticians": "Eyewear (opticians)",
    fashion: "Fashion",
    financialservices: "Financial Services",
    florist: "Florist",
    furniturestore: "Furniture Store",
    grocery: "Grocery",
    healthcare: "Healthcare",
    hobbyshop: "Hobby Shop",
    homeandgarden: "Home And Garden",
    hotel: "Hotel",
    jewelry: "Jewelry",
    landmark: "Landmark",
    library: "Library",
    lingerie: "Lingerie",
    localservices: "Local Services",
    luggage: "Luggage",
    "nurseries.gardening": "Nurseries (gardening)",
    "opera.ballet": "Opera & Ballet",
    performingarts: "Performing Arts",
    petstore: "Pet Store",
    pharmacy: "Pharmacy",
    photographystore: "Photography Store",
    postoffice: "Post Office",
    professionalservices: "Professional Services",
    propertymanagement: "Property Management",
    "publicservices.government": "Public Services (government)",
    "realestate.agents": "Real Estate Agents",
    "realestate.services": "Real Estate Services",
    restaurant: "Restaurant",
    sewingalterations: "Sewing & Alterations",
    shoestore: "Shoe Store",
    shopping: "Shopping",
    specialtyfood: "Specialty Food",
    sportinggoods: "Sporting Goods",
    toystore: "Toy Store",
    travelservices: "Travel Services",
    veterinarian: "Veterinarian",
    watches: "Watches",
  },
  opening: {
    automobile: "Automobile",
    bicycle: "Bicycle",
    emergencyexit: "Emergency Exit",
    pedestrian: "Pedestrian",
    "pedestrian.principal": "Pedestrian (principal)",
    "pedestrian.transit": "Pedestrian (transit)",
    service: "Service",
  },
  relationship: {
    elevator: "Elevator",
    escalator: "Escalator",
    movingwalkway: "Moving Walkway",
    ramp: "Ramp",
    stairs: "Stairs",
    traversal: "Traversal",
    "traversal.path": "Traversal (path)",
  },
  restriction: {
    employeesonly: "Employees Only",
    restricted: "Restricted",
  },
  section: {
    arcade: "Arcade",
    baggageclaim: "Baggage Claim",
    "baggageclaim.intl": "Baggage Claim (international)",
    carrental: "Car Rental",
    "carrental.dropoff": "Car Rental (drop off)",
    checkin: "Check-in",
    concessions: "Concessions",
    cubicle: "Cubicle",
    dutyfree: "Duty Free",
    eatingdrinking: "Eating & Drinking",
    entertainmentarea: "Entertainment Area",
    "entertainmentarea.game": "Entertainment Area (game)",
    "entertainmentarea.music": "Entertainment Area (music)",
    "entertainmentarea.performance": "Entertainment Area (performance)",
    "entertainmentarea.sport": "Entertainment Area (sport)",
    exhibit: "Exhibit",
    exhibition: "Exhibition",
    gambling: "Gambling",
    "gambling.baccarat": "Gambling (baccarat)",
    "gambling.bingo": "Gambling (bingo)",
    "gambling.blackjack": "Gambling (blackjack)",
    "gambling.craps": "Gambling (craps)",
    "gambling.slotmachine.highlimit": "Gambling (high limit slot machine)",
    "gambling.keno": "Gambling (keno)",
    "gambling.poker.letitride": "Gambling (let it ride poker)",
    "gambling.mahjong": "Gambling (mahjong)",
    "gambling.medalgame": "Gambling (medal game)",
    "gambling.minibaccarat": "Gambling (mini baccarat)",
    "gambling.offtrackbetting": "Gambling (off-track betting)",
    "gambling.pachinko": "Gambling (pachinko)",
    "gambling.poker.paigow": "Gambling (pai gow poker)",
    "gambling.paigow": "Gambling (pai gow)",
    "gambling.poker": "Gambling (poker)",
    "gambling.roulette": "Gambling (roulette)",
    "gambling.rummy": "Gambling (rummy)",
    "gambling.sicbo": "Gambling (sic bo)",
    "gambling.slotmachine": "Gambling (slot machine)",
    "gambling.poker.threecard": "Gambling (three card poker)",
    "gambling.poker.video": "Gambling (video poker)",
    gatearea: "Gate Area",
    "gatearea.holding": "Gate Area (holding)",
    immigration: "Immigration",
    "immigration.schengen": "Immigration (Schengen)",
    information: "Information",
    paidarea: "Paid Area",
    parkandride: "Park & Ride",
    parking: "Parking",
    "parking.ev": "Parking (EV)",
    "parking.bicycle": "Parking (bicycle)",
    "parking.compact": "Parking (compact)",
    "parking.longterm": "Parking (long-term)",
    "parking.motorcycle": "Parking (motorcycle)",
    "parking.shortterm": "Parking (short-term)",
    "parking.waitingarea": "Parking (waiting area)",
    platform: "Platform",
    postsecurity: "Post-Security",
    presecurity: "Pre-Security",
    private: "Private",
    recomposearea: "Recompose Area",
    recreation: "Recreation",
    rental: "Rental",
    retail: "Retail",
    retaildepartment: "Retail Department",
    road: "Road",
    seating: "Seating",
    seatingrow: "Seating Row",
    security: "Security",
    servicearea: "Service Area",
    ticketing: "Ticketing",
    vegetation: "Vegetation",
    walkway: "Walkway",
  },
  unit: {
    auditorium: "Auditorium",
    brick: "Brick",
    classroom: "Classroom",
    column: "Column",
    concrete: "Concrete",
    conferenceroom: "Conference Room",
    drywall: "Drywall",
    elevator: "Elevator",
    escalator: "Escalator",
    fieldofplay: "Field Of Play",
    firstaid: "Firstaid",
    fitnessroom: "Fitness Room",
    foodservice: "Food Service",
    footbridge: "Footbridge",
    glass: "Glass",
    huddleroom: "Huddle Room",
    kitchen: "Kitchen",
    laboratory: "Laboratory",
    library: "Library",
    lobby: "Lobby",
    lounge: "Lounge",
    mailroom: "Mail Room",
    mothersroom: "Mothers Room",
    movietheater: "Movie Theater",
    movingwalkway: "Moving Walkway",
    nonpublic: "Non-Public",
    office: "Office",
    opentobelow: "Open to Below",
    parking: "Parking",
    phoneroom: "Phone Room",
    platform: "Platform",
    privatelounge: "Private Lounge",
    ramp: "Ramp",
    recreation: "Recreation",
    restroom: "Restroom",
    "restroom.family": "Restroom (family)",
    "restroom.female": "Restroom (female)",
    "restroom.male": "Restroom (male)",
    "restroom.transgender": "Restroom (transgender)",
    "restroom.unisex": "Restroom (unisex)",
    road: "Road",
    room: "Room",
    serverroom: "Server Room",
    shower: "Shower",
    smokingarea: "Smoking Area",
    stairs: "Stairs",
    steps: "Steps",
    storage: "Storage",
    structure: "Structure",
    theater: "Theater",
    unenclosedarea: "Unenclosed Area",
    unspecified: "Unspecified",
    vegetation: "Vegetation",
    waitingroom: "Waiting Room",
    walkway: "Walkway",
    "walkway.island": "Walkway Island",
    wood: "Wood",
  },
  venue: {
    airport: "Airport",
    "airport.intl": "Airport (international)",
    aquarium: "Aquarium",
    businesscampus: "Business Campus",
    casino: "Casino",
    communitycenter: "Community Center",
    conventioncenter: "Convention Center",
    governmentfacility: "Government Facility",
    healthcarefacility: "Healthcare Facility",
    hotel: "Hotel",
    museum: "Museum",
    parkingfacility: "Parking Facility",
    resort: "Resort",
    retailstore: "Retail Store",
    shoppingcenter: "Shopping Center",
    stadium: "Stadium",
    stripmall: "Strip Mall",
    theater: "Theater",
    themepark: "Theme Park",
    trainstation: "Train Station",
    transitstation: "Transit Station",
    university: "University",
  },
};

Object.keys(categories).forEach((category) => {
  Object.keys(categories[category]).forEach((key) => {
    var uri = `http://register.apple.com/indoor/imdf-sandbox/images/maps-icons/${category}-${key}-default.png`;
    var filepath = `./mapIcons/${category}-${key}.png`;

    const options = {
      url: uri,
      dest: filepath,
      headers: {
        Cookie:
          "s_fid=4302660CA9F32ED3-2EC50E7C93036FC7; s_vi=[CS]v1|2F25E1DD851595D3-40000745E4FBFF7F[CE]; dssf=1; XID=cf04269fcd3f86bc4fc555735c0f0b97; s_vnum_n2_us=19|1,4|2; PLAY_MAPS_CONNECT_LANG=en; s_cc=true; s_sq=awdregisterapple%3D%2526pid%253Dapple%252520business%252520register%252520main%2526pidt%253D1%2526oid%253Dhttps%25253A%25252F%25252Fidmsa.apple.com%25252FIDMSWebAuth%25252Fsignin%25253FappIdKey%25253D9a5e808b031e0daca0bebbe75839e421f855c55dfd3f9c97%2526ot%253DA; dslang=US-EN; geo=TR; ccl=RcB0M5a6DzEbU1G7z3XUQQ==; site=USA; acn01=97+TnIYpRrHY00RqvSbVhlBGW+yLVRR5s22w714AHLmTuNGL7g==; myacinfo=DAWTKNV2f11babf032127c421bb68b3ab9c8f12fd4a0ab7d582fe52c30cfdb8971febb248e2bc8c96697ba2932e392122fe85da07164c77e19b5fd789af614073268de69d5978457cbac857fda79f3877569758f19b760a81835a60530021485a8bc2e5bbfd9a80fe3eab647b0095a501caed023cd5a919afa41c477b7bb151cee9efa603007bf9724365d8d5ec4cb6ff6290bb4d9ffeae8fe95de24d2d111f0c4e39c00bb7f77060ad54e33d59e9d1a833da87ccf5cb177eaee085a7066ef54dabc91733c5fe338268cf3763441056ad58868c3f8ed78f1d23b8ddfc28571950a4ac3cb2c5376f3e18f2f64eece1bd2402003fb7acf720caf0a468d797aaf50a4e53035743a21cef9394c47fe5cee5565b239a7af8c3243509de9eb58e6335d01062e85cfc7419e3c92ef89077f125f2ea8d87f256cb63bd359af1c047d13324d94e9109a06da2fdbc3a06c16f46ceab7ec288440c4c4b58f6eb8abaa9a0cb21808812411aa9a199b39ba8ddbf00f81140502ff66656536353631303637323836306137353735636135303737313236306636336532363039383638MVRYV2; PLAY_MAPS_CONNECT_SESSION=2-GYslGoUZA9xsAo2N/WyHp0f7GdjCoY1zk+E23+434T7fK3uT50tH1CE4zGEw/t1cek1qe2hTJkYuTDEoFAXtx3rqktwEB+xqKW9lgyhlSwQLCqxvWgI6NxUCtJnzdE+6IWXlzO7aqO8SgOFTDrIhUaSpIohahT5m2XNkhjcsqjEgApZgmrj30wdA808Tfrqv+88fQLYtbuWgEuLSlHXLcbI5TpCsb2qGA2tfA2qnPrgpvoDIy9oJrjQRojM7fI+KxurgHFuVQ3nDUom4ycN27vNVxgYZEJniMUdmFRnqsIG5Nk+PUS4caHs7fvrdfN09FRm0bkVh0kr/2/8e0DdJ0zZHr87U6FHqQtfQTKw/q8GWj8AvpCCv9JcVcGIzTSVGB+2DamNMHlixdjNOTjeeD8/cE2bBYfhhdWCny1DLkHzRfLi6DDk9CLNgqfy27Gvfnj3giZLbrww5OWZSyeu/4Dal7Z0J1BbjfMhiMM/MNDZxExcTc5Y8+gCwty3gkpnwjX5ZeFKUmSOLusLqEVqchz1miupOREHUjJydSTUUNiw3GuM/7EAyAFMF7mlkd+EcMVdgfSxndtKthEBeFlL+F8UbF3CqlTNixVEzFSW2CpyLR97M5Y2dgAQ=; NSC_JOntgf2ueo2rdegczhkc0vclojzt2b7=ffffffff1266b50645525d5f4f58455e445a4a4212d3",
      },
    };

    download
      .image(options)
      .then(({ filename, image }) => {
        console.log("Saved to", filename);
      })
      .catch((err) => console.error(err));
  });
});
